const usersActions = {
  ADMIN_USERS_LIST_REQUEST: 'ADMIN_USERS_LIST_REQUEST',
  ADMIN_USERS_LIST_SUCCESS: 'ADMIN_USERS_LIST_SUCCESS',
  ADMIN_USERS_LIST_ERROR: 'ADMIN_USERS_LIST_ERROR',
  ADMIN_CREATE_USER_REQUEST: 'ADMIN_CREATE_USER_REQUEST',
  ADMIN_CREATE_USER_SUCCESS: 'ADMIN_CREATE_USER_SUCCESS',
  ADMIN_CREATE_USER_ERROR: 'ADMIN_CREATE_USER_ERROR',
  ADMIN_UPDATE_USER_REQUEST: 'ADMIN_UPDATE_USER_REQUEST',
  ADMIN_UPDATE_USER_SUCCESS: 'ADMIN_UPDATE_USER_SUCCESS',
  ADMIN_UPDATE_USER_ERROR: 'ADMIN_UPDATE_USER_ERROR',
  ADMIN_DELETE_USER_REQUEST: 'ADMIN_DELETE_USER_REQUEST',
  ADMIN_DELETE_USER_SUCCESS: 'ADMIN_DELETE_USER_SUCCESS',
  ADMIN_DELETE_USER_ERROR: 'ADMIN_DELETE_USER_ERROR',
  fetchList: () => ({
    type: usersActions.ADMIN_USERS_LIST_REQUEST,
  }),
  saveUser: (payload) => ({
    payload,
    type: payload.id
      ? usersActions.ADMIN_UPDATE_USER_REQUEST
      : usersActions.ADMIN_CREATE_USER_REQUEST
  }),
  deleteUser: (payload) => ({
    type: usersActions.ADMIN_DELETE_USER_REQUEST,
    payload,
  }),
};
export default usersActions;
