const modules = {
  ADMIN_MODULES_LIST_REQUEST: 'ADMIN_MODULES_LIST_REQUEST',
  ADMIN_MODULES_LIST_SUCCESS: 'ADMIN_MODULES_LIST_SUCCESS',
  ADMIN_MODULES_LIST_ERROR: 'ADMIN_MODULES_LIST_ERROR',
  fetchList: () => ({
    type: modules.ADMIN_MODULES_LIST_REQUEST,
  }),
};
export default modules;
