const categoriesActions = {
  ADMIN_CATEGORIES_LIST_REQUEST: 'ADMIN_CATEGORIES_LIST_REQUEST',
  ADMIN_CATEGORIES_LIST_SUCCESS: 'ADMIN_CATEGORIES_LIST_SUCCESS',
  ADMIN_CATEGORIES_LIST_ERROR: 'ADMIN_CATEGORIES_LIST_ERROR',
  ADMIN_CREATE_CATEGORY_REQUEST: 'ADMIN_CREATE_CATEGORY_REQUEST',
  ADMIN_CREATE_CATEGORY_SUCCESS: 'ADMIN_CREATE_CATEGORY_SUCCESS',
  ADMIN_CREATE_CATEGORY_ERROR: 'ADMIN_CREATE_CATEGORY_ERROR',
  ADMIN_UPDATE_CATEGORY_REQUEST: 'ADMIN_UPDATE_CATEGORY_REQUEST',
  ADMIN_UPDATE_CATEGORY_SUCCESS: 'ADMIN_UPDATE_CATEGORY_SUCCESS',
  ADMIN_UPDATE_CATEGORY_ERROR: 'ADMIN_UPDATE_CATEGORY_ERROR',
  ADMIN_DELETE_CATEGORY_REQUEST: 'ADMIN_DELETE_CATEGORY_REQUEST',
  ADMIN_DELETE_CATEGORY_SUCCESS: 'ADMIN_DELETE_CATEGORY_SUCCESS',
  ADMIN_DELETE_CATEGORY_ERROR: 'ADMIN_DELETE_CATEGORY_ERROR',
  fetchList: () => ({
    type: categoriesActions.ADMIN_CATEGORIES_LIST_REQUEST,
  }),
  saveCategory: (payload) => ({
    payload,
    type: payload.id
      ? categoriesActions.ADMIN_UPDATE_CATEGORY_REQUEST
      : categoriesActions.ADMIN_CREATE_CATEGORY_REQUEST
  }),
  deleteCategory: (payload) => ({
    type: categoriesActions.ADMIN_DELETE_CATEGORY_REQUEST,
    payload,
  }),
};
export default categoriesActions;
