const modulesActions = {
  ADMIN_USER_MODULES_LIST_REQUEST: 'ADMIN_USER_MODULES_LIST_REQUEST',
  ADMIN_USER_MODULES_LIST_SUCCESS: 'ADMIN_USER_MODULES_LIST_SUCCESS',
  ADMIN_USER_MODULES_LIST_ERROR: 'ADMIN_USER_MODULES_LIST_ERROR',
  ADMIN_USER_MODULES_UPDATE_REQUEST: 'ADMIN_USER_MODULES_UPDATE_REQUEST',
  ADMIN_USER_MODULES_UPDATE_SUCCESS: 'ADMIN_USER_MODULES_UPDATE_SUCCESS',
  ADMIN_USER_MODULES_UPDATE_ERROR: 'ADMIN_USER_MODULES_UPDATE_ERROR',
  fetchList: () => ({
    type: modulesActions.ADMIN_USER_MODULES_LIST_REQUEST,
  }),
};
export default modulesActions;
